### ISSUE TITLE
Start Postgres server in WSL

### ISSUE THREAD

**Issue by kennydude** [agowa338/WSL-DistroLauncher-Alpine#23]
I've installed postgresql using the `su -c "apk install postgresql"` but I cannot seem to get it to install. I tried installing openrc, but it gives me some scary warnings about it not having much control over boot (as it's not a normal boot iirc?).

Any tips for running "normal" services appreciated

**Comment by agowa338** [comment]
I'd recommend not using wsl directly for that. The best option is to use docker, as that will allow one to have greater control over where the files are placed (volumes), free you from wired side effects, provide a deterministic environment, allows to use restart policies to restart after the computer reboots. Also allows to just c'n'p the configuration onto any cloud environment. And finally docker for windows uses the wsl system apis internally. If you'd like you can also activate kubernetes (k8s) within the docker for windows client. That will spawn a full k8s environment on your node and that way you'll have even more possibilities.

The "WSL distros" are more intended for ad-hoc commands, like in this example:
`wsl.exe pwgen 20 1` or `docker.exe ps -aq | wsl.exe xargs docker.exe rm`, where pwgen and xargs are commands installed within wsl and are either not available on windows or are just simpler to setup that way.
It is not suitable for long running services. That does not mean, that you couldn't use it for that, but more that there are better options instead.

Anyway, here is the docker example:
```yaml
version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=aehoo7xaPh2zemoofeik
      - POSTGRES_PASSWORD=ooS5raengeeb9ej0Cee2
    deploy:
      condition: any
      delay: 1s
      max_attempts: 2
      window: 120s
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:  
```

And if yoy still like to use the wsl distro for that instead create a shortcut at your desktop or a scheduled job to start the postgresql daemon. e.g. like this:  https://devblogs.microsoft.com/scripting/use-powershell-to-create-job-that-runs-at-startup/
WSL uses it's own custom init system and that cannot be swapped for a different one. For more, here is a good write up for ubuntu the wsl specific parts mostly apply to all wsl distros. https://wiki.ubuntu.com/WSL#Keeping_Ubuntu_Updated_in_WSL
